name: Spacegame.Web
on:
 push:
   branches: [ main ]
 pull_request:
   branches: [main]
 

jobs:
    build_api_app:
      name: 🧪 Build API App
      runs-on: ubuntu-latest
      
      steps:
      - uses: actions/checkout@v2
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
          
      - uses: actions/cache@v3
        with:
         path: ~/.nuget/packages
         key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
         restore-keys: |
          ${{ runner.os }}-nuget-
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --no-restore
             
